image: samueldebruyn/debian-git

# Base directory is home/uihnkvpp/wp_graal/wp-content/themes/

pipelines:
  branches:
    deploy/prod:
      - step:
          script:
            - apt-get update
            - apt-get -qq install git-ftp
            - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD "ftp://91.197.228.162/graal-archive"